server:
  port: 9003

spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: group-account
  application:
    name: banking_transaction_service
  datasource:
    url: jdbc:mysql://localhost:3306/banking_transaction?createDatabaseIfNotExist=true
    username: root
#    password: 29082001
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
