version: "3.9"

networks:
  app-network:
    driver: bridge

volumes:
  db-service-1:
  db-service-2:
  db-service-3:
  kong-data:

services:
  db-service-1:
    image: mysql:8.0.32  
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=banking_manager_user
    networks:
      - app-network
    volumes:
      - ./db-service-1:/var/lib/mysql 

  service-1: 
    build: ./banking_manager_user_service
    ports:
      - "9000:9000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service-1:3306/banking_manager_user
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - app-network
    depends_on:
      - db-service-1
      - config-server

  db-service-2:
    image: mysql:8.0.32  
    ports:
      - "3308:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=banking_account_currency
    networks:
      - app-network
    volumes:
      - ./db-service-2:/var/lib/mysql 

  service-2: 
    build: ./banking_account_currency_service
    ports:
      - "9002:9002"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service-2:3306/banking_account_currency
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - app-network
    depends_on:
      - db-service-2
      - config-server
      - kafka
      - zookeeper

  db-service-3:
    image: mysql:8.0.32  
    ports:
      - "3309:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=banking_transaction
    networks:
      - app-network
    volumes:
      - ./db-service-3:/var/lib/mysql 

  service-3: 
    build: ./banking_transaction_service
    ports:
      - "9003:9003"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service-3:3306/banking_transaction
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - app-network
    depends_on:
      - db-service-3
      - config-server
      - kafka
      - zookeeper 

  log-service:
    build: ./BalanceLogService
    ports:
      - "9004:9004" 
    networks:
      - app-network
    depends_on:
      - service-3
      - db-service-3
      - kafka
      - zookeeper 

  config-server:
    build: ./banking_config_server
    ports:
      - "9999:9999" 
    networks:
      - app-network 

  zookeeper:
    image: wurstmeister/zookeeper 
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka 
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - app-network

  kong-database:
    image: postgres:13
    networks:
      - app-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - ./kong-data:/var/lib/postgresql/data

  kong-migrations:
    image: kong/kong-gateway:3.6-debian
    networks:
      - app-network
    environment:
      KONG_PG_HOST: kong-database
      KONG_DATABASE: postgres
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: kong
    command: kong migrations bootstrap
    depends_on:
      - kong-database

  kong-gateway:
    image: kong/kong-gateway:3.6-debian
    networks:
      - app-network
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    #      KONG_PLUGINS: bundled,sync-eureka
    #      KONG_LICENSE_DATA: # Insert license data here
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    depends_on:
      - kong-database
      - kong-migrations

  discovery-syncer:
    build: ./banking-kong-gateway
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - eureka-server
      - kong-gateway

  eureka-server:
    build: ./banking_eureka_server
    ports:
      - "8761:8761"
    networks:
      - app-network

  # app-frontend-ng:
  #   image: belemon81/internship:pro-bookstore-ng
  #   # build: ./BookStore_FE_Angular
  #   ports:
  #     - "4200:4200"
  #   networks:
  #     - app-network
  #   depends_on:
  #     - app-backend
