enable-pprof: false
logger:
    level: debug
    logger: console
    log-file: syncer.log
    date-slice: y

discovery-servers:
#    # nacos1 是注册中心的名字，可以随便定义，但是不能重复
#    nacos1:
#        # 类型，目前仅支持 nacos和eureka
#        type: nacos
#        # 默认，如果注册中心没有返回权重时，添加的默认权重
#        weight: 100
#        # 注册中心的url前缀
#        prefix: /nacos/v1/
#        # 注册中心的连接地址，注意最后不能带/
#        host: "http://nacos-server:8858"
    eureka1:
        type: eureka
        weight: 100
        prefix: /eureka/
        host: "http://admin:admin@eureka-server:8761"

gateway-servers:
    # 网关名字，可以随便写，但是不能重复
#    apisix1:
#        # 网关类型，目前支持apisix和kong
#        type: apisix
#        # 管理端host,注意最后不能有/
#        admin-url: http://apisix-server:9080
#        # 管理端uri前缀
#        prefix: /apisix/admin/
#        # 特别的扩展参数，在config里用key:value形式添加
#        config:
#            X-API-KEY: xxxxx
#            # apisix admin api 目前2.15.x 和 3.x 差异较大 详见 https://apisix.apache.org/zh/docs/apisix/next/upgrade-guide-from-2.15.x-to-3.0.0/
#            # 默认是v2，如果是3.x的，请改成v3
#            version: v2
    kong1:
        type: kong
        admin-url: http://kong-server:8001
        prefix: /upstreams/

targets:
#    -   discovery: nacos1
#        gateway: apisix1
#        enabled: false
#        fetch-interval: "@every 10s"
#        exclude-service: [ 'ex*','test' ]
#        upstream-prefix: nacos1
#        name: nacos1-apisix1
#        maximum-interval-sec: 20
#        # 扩展参数
#        config:
#            # nacos 的groupName
#            groupName: DEFAULT_GROUP
#            # nacos的 namespace
#            namespaceId: test
#            # 创建到apisix 的upstream的默认模板，具体支持的模板语法，自行搜索 golang text/template
#            template: |
#                {
#                    "id": "{{.Name}}",
#                    "timeout": {
#                        "connect": 30,
#                        "send": 30,
#                        "read": 30
#                    },
#                    "name": "{{.Name}}",
#                    "nodes": {{.Nodes}},
#                    "type":"roundrobin",
#                    "desc": "auto sync by https://github.com/anjia0532/discovery-syncer"
#                }

    -   discovery: eureka1
        gateway: kong1
        enabled: false
        fetch-interval: "@every 5s"
        maximum-interval-sec: 10
        config:
            template: |
                {
                    "name": "{{.Name}}",
                    "algorithm": "round-robin",
                    "hash_on": "none",
                    "hash_fallback": "none",
                    "hash_on_cookie_path": "/",
                    "slots": 10000,
                    "healthchecks": {
                        "passive": {
                            "healthy": {
                                "http_statuses": [200, 201, 202, 203, 204, 205, 206, 207, 208, 226, 300, 301, 302, 303, 304, 305, 306, 307, 308],
                                "successes": 0
                            },
                            "type": "http",
                            "unhealthy": {
                                "http_statuses": [429, 500, 503],
                                "timeouts": 0,
                                "http_failures": 0,
                                "tcp_failures": 0
                            }
                        },
                        "active": {
                            "timeout": 1,
                            "https_sni": "example.com",
                            "http_path": "/",
                            "concurrency": 10,
                            "https_verify_certificate": true,
                            "type": "http",
                            "healthy": {
                                "http_statuses": [200, 302],
                                "successes": 0,
                                "interval": 0
                            },
                            "unhealthy": {
                                "http_statuses": [429, 404, 500, 501, 502, 503, 504, 505],
                                "timeouts": 0,
                                "http_failures": 0,
                                "interval": 0,
                                "tcp_failures": 0
                            }
                        },
                        "threshold": 0
                    },
                    "tags": ["discovery-syncer-auto"]
                }